# Generated by Django 2.0.1 on 2018-01-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prekey',
            name='key_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='prekey',
            unique_together={('account', 'key_id')},
        ),
    ]
